backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    label_singular: "Portfolio Item"
    folder: "public/portfolio"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    identifier_field: "label"
    fields:
      - {label: "Project Title", name: "label", widget: "string"}
      - {label: "Work Description", name: "detail", widget: "string"}
      - {label: "Before Photo", name: "before", widget: "image"}
      - {label: "After Photo", name: "after", widget: "image"}
      - {label: "Wide Card", name: "wide", widget: "boolean", default: false}
      - {label: "Display Order", name: "order", widget: "number", default: 99}
